FROM alpine:latest AS builder

RUN apk --no-cache add bash wget curl unzip\
    # 根据平台动态下载 rclone
    && version=$(echo $(curl -fsS https://downloads.rclone.org/version.txt)|grep -o v.*) \
    && [ "$(uname -m)" = "x86_64" ] && OS_type=amd64 || OS_type=arm64 \
    && wget https://github.com/rclone/rclone/releases/download/${version}/rclone-${version}-linux-${OS_type}.zip \
    # 解压文件
    && unzip rclone-${version}-linux-${OS_type}.zip \
    && cp rclone-${version}-linux-${OS_type}/rclone /usr/local/bin/rclone 

RUN wget https://github.com/cryptomator/cli/releases/download/0.5.1/cryptomator-cli-0.5.1.jar -O /usr/bin/cryptomator.jar

# 尝试使用24
#FROM alpine
FROM aehrc/jre:openjdk-17
#FROM openjdk:17-slim
# FROM openjdk:11-jre-slim
# JDK 会增大图像大小，只需要 JRE。但没有 17-JRE 版本
# 最低java17

WORKDIR /app

ENV VAULT_NAME=demoVault \
    VAULT_PATH=/rclone-mount \
    VAULT_PASS=password \
    VAULT_BIND=0.0.0.0 \
    CRYPTOMATOR_PORT=5005 \
    VAULT_MOUNT=/mnt \
    URL="" \
    REMOTE=""

EXPOSE 5005

COPY --from=builder /usr/local/bin/rclone /usr/local/bin/rclone
COPY --from=builder /usr/bin/cryptomator.jar /usr/bin/cryptomator.jar

COPY supervisord/*.sh /app/

# 安装fuse2，要不然报错，毕竟21年的程序
# 但是rclone又是用fusermount3
# 同时安装又会报错，只能用软连接了

RUN apk --no-cache add wget fuse supervisor \
    && echo "user_allow_other" >> /etc/fuse.conf \
    && ln -s $(which fusermount) /usr/bin/fusermount3 \
    && mkdir -p /etc/supervisor/conf.d \
    && chmod +x /usr/local/bin/rclone \
    && chmod +x /app/*.sh \
    && touch /var/log/supervisord.log

COPY supervisord/supervisord.conf /etc/supervisor/conf.d/

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
