name: chevereto
services:
    php-fpm:
        build: ./app
        volumes:
            - './chevereto:/var/www/html'
        networks:
            - app-network

    web:
        build: ./web
      #image: nginx
      #hostname: chevereto
        networks:
            - app-network
        ports:
            - '8080:80'
        volumes:
            - './chevereto:/var/www/html'
              #    - './web/nginx.conf:/etc/nginx/nginx.conf'
              #- './web/rewrite.conf:/etc/nginx/rewrite.conf'
        depends_on:
            - php-fpm

networks:
    app-network:
        driver: bridge
