# 使用 Nginx Alpine 版本作为基础镜像
FROM --platform=$TARGETPLATFORM nginx:alpine AS build

# 设置工作目录
WORKDIR /home/mtproxy

# 安装必要的软件包并克隆 GitHub 存储库
RUN apk update && apk upgrade && apk add --no-cache git php7-fpm curl bash && \
    git clone https://github.com/ellermister/mtproxy.git /home/mtproxy && \
    cp src/* /usr/share/nginx/html && \
    cp mtproxy-entrypoint.sh /docker-entrypoint.d/40-mtproxy-start.sh && \
    chmod +x /docker-entrypoint.d/40-mtproxy-start.sh && \
    cp -f nginx/default.conf /etc/nginx/conf.d/default.conf && \
    cp -f nginx/ip_white.conf /etc/nginx/ip_white.conf && \
    cp -f nginx/nginx.conf /etc/nginx/nginx.conf && \
    bash mtproxy.sh build && \
    sed -i 's/^user\s*=[^\r]\+/user = root/' /etc/php7/php-fpm.d/www.conf && \
    sed -i 's/^group\s*=[^\r]\+/group = root/' /etc/php7/php-fpm.d/www.conf && \
    mkdir -p /run/php && mkdir /home/mtproxy/pid

# 清理不必要的文件
RUN apk del git && \
    rm -rf /var/cache/apk/* /home/mtproxy/MTProxy

# 暴露端口
EXPOSE 80 443
ENTRYPOINT ["/docker-entrypoint.d/40-mtproxy-start.sh"]
