services:
    dante:
        image: yujibuzailai/dante
        command: sockd-username
        environment:
            SOCKD_USER_NAME: $SOCKD_USER_NAME
            SOCKD_USER_PASSWORD: $SOCKD_USER_PASSWORD
        ports:
            - 1080:1080
        #volumes:
        #    - ./sockd.conf:/etc/sockd.conf
