name: "Docker Build ip_derper"

on:
  workflow_dispatch: # 手动运行
#  push: # 推送
#    branches: [ "main" ]

#  pull_request: # 拉取
#    branches: [ "main" ]
    
#  watch: # 手动点击收藏
#    types: [started]
jobs:
  build_image:
    runs-on: ubuntu-latest #申请一个ubuntu的虚拟机

    steps:
      - name: Checkout Code # 第一步，获取代码
        uses: actions/checkout@v4 # 官方的action，获取代码

      - name: Build image # 第二步，构建docker镜像
        run: |
          ls -la
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ip_derper \
            -f ./ip_derper/Dockerfile \
            .

      - name: Log in to Docker Hub # 登录docker hub
        uses: docker/login-action@v3  # 三方的action操作， 执行docker login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

 #     - name: Push image # 第四步，推送镜像到docker hub 
 #       run: |
 #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/ip_derper
